Web/Areas/Panel/Controllers/UserManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Data.Dtos;
using Data.Interfaces;
using Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Web.Areas.Panel.Controllers
{
    [Area("Panel")]
    public class UserManageController : Controller
    {
        private readonly UserManager<AppUser> _userManage;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;
        public UserManageController(UserManager<AppUser> userManage, IMapper mapper, RoleManager<IdentityRole> roleManager)
        {
            _userManage = userManage;
            _mapper = mapper;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAllUsers()
        {
            try
            {
                var getUsers = await _userManage.Users.ToListAsync();
             //   var roles = _roleManager.Roles.ToList();
                foreach (var user in getUsers)
                        if(await _userManage.IsInRoleAsync(user, "Admin"))
                            user.Roles = "مدیر";
                var query = _mapper.Map<List<AppUser>, List<UserListDto>>(getUsers);
                return Ok(query);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

    }
}

Web/Areas/Panel/Views/Shared/Partials/_menuBar.cshtml
@{
    Layout = null;
}
    <li class="nav-item">
        <a asp-area="Panel" asp-controller="Panel" asp-action="Dashboard" class="nav-link">
            <i class="nav-icon fa fa-th"></i>
            <p>
                داشبورد
            </p>
        </a>
    </li>
<li class="nav-item has-treeview menu-open">
    <a href="#" class="nav-link active">
        <i class="nav-icon fa fa-users"></i>
        <p>
            بخش کاربری
            <i class="right fa fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a asp-area="Panel"asp-controller="UserManage" asp-action="Index"  class="nav-link">
                <i class="fa fa-user-circle nav-icon"></i>
                <p>مدیریت کاربران</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="fa fa-circle-o nav-icon"></i>
                <p>صفحه غیر فعال</p>
            </a>
        </li>
    </ul>
</li>
<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fa fa-th"></i>
        <p>
            لینک ساده
            <span class="right badge badge-danger">جدید</span>
        </p>
    </a>
</li>
<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fa fa-th"></i>
        <p>
            لینک ساده
            <span class="right badge badge-danger">جدید</span>
        </p>
    </a>
</li>